### ISSUE TITLE
Does this work with latest deepstream server?

### ISSUE THREAD

**Issue by illogikal** [Currency-One/deepstream-ruby#22]

**Comment by thisredone** [comment]
not yet but there's upgrade in progress

**Comment by illogikal** [comment]
Is it public? Maybe I can help?

**Comment by thisredone** [comment]
I think we got this. Thanks though :)
Next version is going to based on [async](https://github.com/socketry/async)

**Comment by illogikal** [comment]
Any idea on when it is likely to come out? :)

**Comment by thisredone** [comment]
I'd say few weeks

**Comment by illogikal** [comment]
It's out?

**Comment by thisredone** [comment]
yep :}
